// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVMOGlyVbyqadUan8W71KmJp7qqb59_4w',
    appId: '1:930447149134:web:2e14e4dab8676072135b1f',
    messagingSenderId: '930447149134',
    projectId: 'shortplex-edd87',
    authDomain: 'shortplex-edd87.firebaseapp.com',
    storageBucket: 'shortplex-edd87.appspot.com',
    measurementId: 'G-59XMMVVJ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyGMF9-txJPalMSrJM9wqjWCiqPYOtZvA',
    appId: '1:930447149134:android:90eebaffc525b571135b1f',
    messagingSenderId: '930447149134',
    projectId: 'shortplex-edd87',
    storageBucket: 'shortplex-edd87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9eR82Sg-bic0aX_ZrLKyaEADXtVFfBBQ',
    appId: '1:930447149134:ios:bd4c2d04f6aebd49135b1f',
    messagingSenderId: '930447149134',
    projectId: 'shortplex-edd87',
    storageBucket: 'shortplex-edd87.appspot.com',
    iosBundleId: 'com.shortplex.shortplex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9eR82Sg-bic0aX_ZrLKyaEADXtVFfBBQ',
    appId: '1:930447149134:ios:bd4c2d04f6aebd49135b1f',
    messagingSenderId: '930447149134',
    projectId: 'shortplex-edd87',
    storageBucket: 'shortplex-edd87.appspot.com',
    iosBundleId: 'com.shortplex.shortplex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVMOGlyVbyqadUan8W71KmJp7qqb59_4w',
    appId: '1:930447149134:web:3dd855c4a44400cd135b1f',
    messagingSenderId: '930447149134',
    projectId: 'shortplex-edd87',
    authDomain: 'shortplex-edd87.firebaseapp.com',
    storageBucket: 'shortplex-edd87.appspot.com',
    measurementId: 'G-Y3ZLBFPXDK',
  );

}